In [2]:
# Bag of words collection numbered unique words counts
#                     -add auto I and help need urgent
# -i need help,help!   [ 0   0  1  0   2    1    0]
# >if bag of word is 10k size then our whole email will be 10k size
# >unlike one hot encoding in which 1 word is of 10k size
# >it does not capture meaning of word, only count


In [27]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df["Category"].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [6]:
df["spam"] = df.Category.apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(df["Message"],df['spam'],test_size=0.2)
len(x_train)

4457

In [11]:
type(x_train)

pandas.core.series.Series

In [12]:
x_train[:5]

C:\Users\Janak\AppData\Local\Temp\ipykernel_23412\249614703.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  x_train[:5]


4661    You call him and tell now infront of them. Cal...
2501                 Remember to ask alex about his pizza
767     I'm nt goin, got somethin on, unless they meet...
3439                            Its good to hear from you
4305    Good good, billy mates all gone. Just been jog...
Name: Message, dtype: object

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
# .values convert the series into numpy array
x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<4457x7726 sparse matrix of type '<class 'numpy.int64'>'
	with 59110 stored elements in Compressed Sparse Row format>

In [17]:
x_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
x_train_cv.shape
# 7726 unique words

(4457, 7726)

In [22]:
# getting the words in vocabulary
v.get_feature_names_out()[1000:2000]

array(['antibiotic', 'any', 'anybody', 'anymore', 'anyone', 'anythiing',
       'anythin', 'anything', 'anythingtomorrow', 'anytime', 'anyway',
       'anyways', 'anywhere', 'aom', 'apart', 'apartment', 'apes',
       'apeshit', 'aphex', 'apnt', 'apo', 'apologise', 'apologize',
       'apology', 'app', 'apparently', 'appear', 'applausestore',
       'applebees', 'apples', 'application', 'apply', 'applying',
       'appreciate', 'appreciated', 'approaches', 'approaching',
       'appropriate', 'approve', 'approx', 'apps', 'appt', 'appy',
       'april', 'aproach', 'apt', 'aptitude', 'aquarius', 'ar', 'arab',
       'arabian', 'arcade', 'archive', 'ard', 'are', 'area', 'aren',
       'arent', 'aretaking', 'areyouunique', 'argentina', 'argh', 'argue',
       'argument', 'arise', 'arithmetic', 'arm', 'armand', 'arms', 'arng',
       'arngd', 'around', 'aroundn', 'arr', 'arrange', 'arranging',
       'arrested', 'arrival', 'arrive', 'arrived', 'arrow', 'arsenal',
       'art', 'artists', 'a

In [23]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [24]:
# getting the number assing to words in vocublary
v.vocabulary_

{'you': 7686,
 'call': 1610,
 'him': 3421,
 'and': 969,
 'tell': 6733,
 'now': 4824,
 'infront': 3672,
 'of': 4875,
 'them': 6801,
 'remember': 5671,
 'to': 6906,
 'ask': 1093,
 'alex': 910,
 'about': 763,
 'his': 3427,
 'pizza': 5215,
 'nt': 4830,
 'goin': 3154,
 'got': 3181,
 'somethin': 6295,
 'on': 4918,
 'unless': 7140,
 'they': 6815,
 'meetin': 4402,
 'dinner': 2327,
 'lor': 4189,
 'haha': 3282,
 'wonder': 7555,
 'who': 7472,
 'will': 7495,
 'go': 3145,
 'tis': 6889,
 'time': 6877,
 'its': 3756,
 'good': 3167,
 'hear': 3361,
 'from': 2999,
 'billy': 1362,
 'mates': 4361,
 'all': 918,
 'gone': 3164,
 'just': 3860,
 'been': 1298,
 'jogging': 3822,
 'again': 862,
 'did': 2297,
 'enjoy': 2588,
 'concert': 1947,
 'sounds': 6330,
 'fingers': 2841,
 'makes': 4309,
 'it': 3751,
 'difficult': 2311,
 'type': 7077,
 'designation': 2257,
 'is': 3740,
 'software': 6278,
 'developer': 2275,
 'may': 4376,
 'be': 1276,
 'she': 6060,
 'get': 3101,
 'chennai': 1768,
 'reach': 5574,
 'ur': 7170,
 '

In [26]:
x_train_np = x_train_cv.toarray()
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
np.where(x_train_np[0]!=0)

(array([ 969, 1610, 3421, 3672, 4824, 4875, 6733, 6801, 7686], dtype=int64),)

In [29]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [30]:
x_test_cv = v.transform(x_test)

In [32]:
from sklearn.metrics import classification_report
y_pred = model.predict(x_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       964
           1       0.95      0.90      0.93       151

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [33]:
emails = [
    "Hello brother, how are you?, Today i am arriving at airport.",
    "50% off on Amazon Great Indian Sale!! Click on the link below for discount."
]

email_cv = v.transform(emails)
model.predict(email_cv)

array([0, 1], dtype=int64)

In [34]:
# above all things can be done through sklearn pipeline
# it does everthing automatically first through count vectorizer then model multimonial nb
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [35]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [36]:
print(classification_report(y_test,clf.predict(x_test)))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       964
           1       0.95      0.90      0.93       151

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

